### PR TITLE
Replace WowDude/Pornlist to an another updated one.

### PR DESCRIPTION
**Pull request by PoorPocketsMcNewHold**
### URL(s) where the issue occurs

```
https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/Anti-Corp/Spotify/Spotify-AdBlock.txt
https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/nsablocklist.txt​​
https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/ccleaner.txt
https://raw.githubusercontent.com/WowDude/PornList/master/PornList.txt​​
https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/CK's-FilterList-slimm.txt
https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/luckypatcher.txt
```

### Describe the issue

As you can see, your lists are not reachable, some were just moved on their repo, so I’ve updated their links :
https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/Anti-Corp/Spotify/Spotify-AdBlock.txt​​​​​ became https://raw.githubusercontent.com/CHEF-KOCH/Spotify-Ad-free/master/filter/Spotify-AdBlock.txt
https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/nsablocklist.txt​​ became https://raw.githubusercontent.com/CHEF-KOCH/NSABlocklist/master/HOSTS/HOSTS
Other had to be changed for alternatives : 
https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/ccleaner.txt​​ became https://raw.githubusercontent.com/CHEF-KOCH/NSABlocklist/master/HOST  you’ve merged the Avast telemetry domains with the Ccleaner ones (Since they belong to the same company)
https://raw.githubusercontent.com/WowDude/PornList/master/PornList.txt​​ became https://raw.githubusercontent.com/eEIi0A5L/adblock_filter/master/ichigo_filter.txt as the user WowDude was deleted, so I replaced it with another project who block pornographic ads (And not a pornographic website blocker, I’m aware of what the PornList was about).

However, I had to delete some lists since I didn’t find any alternatives : 
https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/CK's-FilterList-slimm.txt became https://raw.githubusercontent.com/CHEF-KOCH/BarbBlock-filter-list/master/uBlock.txt as you deleted your own general purposes filterlist (I suppose it was just a compilation of multiples lists anyway, I’m wrong ?) I’ve choosed to introduce the BarbBlock filterlist that way.
And fully deleted the https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/luckypatcher.txt​ list has I didn’t found any replacements.

### Versions

(Not related to the adblocker software)

### Settings

(Not related to the adblocker software)

### CODE REVIEW

**Comment by CHEF-KOCH** [comment]
GitHub and I are now discussing several internal changes, which means I get my original repository for  back, however we discuss internal ways to avoid any DMCA trolling drama again. It's unclear when this will happen because I'm busy with other stuff and my current eMail response time is like ~1 week.

However, I already added a mirror, for all lists and you can fully access them over [here](https://gitlab.com/CHEF-KOCH/cks-filterlist), I did not updated/corrected or changed the links because I personally want to get them from GitHub (until I self-host my stuff). 

I will not merge your change in this stage (_sorry_) because I simply need to wait. If you want to change the links please use the ones from GitLab or you change and "correct" the links directly on Gitlab mirror (Readme.md links I'm talking about), then I can migrate them as workaround into the blocker database.

**Comment by txtsd** [comment]
@CHEF-KOCH I recommend making gitlab the default.

**Comment by PoorPocketsMcNewHold** [comment]
That's perfectly fine. However, We still got the question with the WowDude PornList filterlist, Do you expect hosting a mirror of it, or should I replace it (Like with the one I’ve set up already)?

**Comment by CHEF-KOCH** [comment]
> We still got the question with the WowDude PornList filterlist, Do you expect hosting a mirror of it, or should I replace it (Like with the one I’ve set up already)?

A replacement for the PornList would be the better idea. So your change is okay and makes (IMHO) the most sense.

**Comment by PoorPocketsMcNewHold** [comment]
> > We still got the question with the WowDude PornList filterlist, Do you expect hosting a mirror of it, or should I replace it (Like with the one I’ve set up already)?
> 
> A replacement for the PornList would be the better idea. So your change is okay and makes (IMHO) the most sense.

Well, Done. I’ve reverted the list, and conserved only the changes to the WowDude/PornList.

**Pull request merged**
